import { signals } from "./jsml/signals.js"

export const I18N = {
    en_us: {
        NAME: "BSim",
        UNNAMED_CIRCUIT: "Unnamed circuit",
        LANGS: {
            EN_US: "English (USA)",
            DE_DE: "German (Germany)",
            LA_RO: "Latin (S.P.Q.R.)",
        },
        SETTINGS: {
            TITLE: "Settings",
            LANGUAGE: "Language",
            GRAPHICS: "Graphics",
            BLUR: "Blur",
            BACKGROUND: "Background",
            BACKGROUND_FLAT: "Flat",
            BACKGROUND_SHADED: "Shaded",
            GATE_SYMBOLS: "Gate symbols",
            GATE_SYMBOLS_ANSI: "ANSI (American)",
            GATE_SYMBOLS_IEC: "IEC (EU)",
            ADVANCED: "Advanced",
            DEBUG_DISPLAY: "FPS graph",
            PERF_GRAPH: "Performance graph",
            PERF_GRAPH_NOTE: "Performance graph might not work correctly on all browsers.\nIn Firefox the privacy.reduceTimerPrecision flag must be set to false",

            HIGH: "High",
            LOW: "Low",
            OFF: "Off",
            SHOW: "Show",
            HIDE: "Hide",
        },
        CATEGORIES: {
            GATES: "Gates",
            IO: "I/O", 
            MISC: "Miscellaneous",
        },
        BLOCKS: {
            AND: "AND",
            OR: "OR",
            XOR: "XOR",
            NOT: "NOT",
            NAND: "NAND",
            NOR: "NOR",
            XNOR: "XNOR",

            TOGGLE: "Toggle",
            LED: "LED",

            DELAY: "Delay",
            NODE: "Node",
        },
        LOOP_CREATED: {
            MAIN: "This is a loop!",
            FIX_MESSAGE_0: "Break up loops with ",
            FIX_MESSAGE_1: "delay blocks",
            FIX_MESSAGE_2: ".",
        },
        KEYBOARD: {
            CTRL_PC: "CTRL",
            META_MAC: "⌘",
            ALT_PC: "ALT",
            ALT_MAC: "⌥",
            SHIFT: "SHIFT",
        },
        TIPS: {
            MOVE_NODE: "Move node",
            DISCONNECT: "Disconnect cable from input",
            INTERACT: "Interact",
            MOVE_BLOCK: "Move block",
        },
        POPUPS: {
            OPEN_FILE: "Open file",
            CLEAR_WARING: "Your existing circuit will be permanently deleted! Consider saving this circuit before continuing.",
            CLEAR_AND_CONTINUE: "Delete & Continue",
            CANCEL: "Cancel",
            ERROR_WHILE_UPLOADING: "An error occured!",

            DOWNLOAD_AND_SHARE: "Download & Share",
            COPY_LINK: "Copy link",
            FORMAT: "Format",
            BINARY: "Binary",
            BINARY_NOTE: "Smaller file size (recommended)",
            JSON: "JSON",
            JSON_NOTE: "Human-readable file format",
            FILE_NAME: "File name",
            DOWNLOAD: "Download",
        }
    },
    de_de: {
        NAME: "BSim",
        UNNAMED_CIRCUIT: "Unbenannter Schaltkreis",
        LANGS: {
            EN_US: "Englisch (USA)",
            DE_DE: "Deutsch (Deutschland)",
            LA_RO: "Latein (S.P.Q.R.)",
        },
        SETTINGS: {
            TITLE: "Einstellungen",
            LANGUAGE: "Sprache",
            GRAPHICS: "Grafik",
            BLUR: "Weichzeichnen",
            BACKGROUND: "Hintergrund",
            BACKGROUND_FLAT: "Einfarbig",
            BACKGROUND_SHADED: "Schattiert",
            GATE_SYMBOLS: "Gatter-Symbole",
            GATE_SYMBOLS_ANSI: "ANSI (Amerikanisch)",
            GATE_SYMBOLS_IEC: "IEC (EU)",
            ADVANCED: "Erweitert",
            DEBUG_DISPLAY: "FPS-Graph",
            PERF_GRAPH: "Performance-Graph",
            PERF_GRAPH_NOTE: `Der Performance-Graph funktioniert evtl. nicht in allen Browsern.\nIn Firefox muss die Flag "privacy.reduceTimerPrecision" auf false gesetzt werden.`,

            HIGH: "Hoch",
            LOW: "Niedrig",
            OFF: "Aus",
            SHOW: "Anzeigen",
            HIDE: "Verstecken",
        },
        CATEGORIES: {
            GATES: "Gatter",
            IO: "I/O",
            MISC: "Anderes",
        },
        BLOCKS: {
            AND: "UND",
            OR: "ODER",
            XOR: "EX. ODER",
            NOT: "NICHT",
            NAND: "NAND",
            NOR: "NOR",
            XNOR: "XNOR",

            TOGGLE: "Schalter",
            LED: "LED",
            
            DELAY: "Verzögerung",
            NODE: "Knoten",
        },
        LOOP_CREATED: {
            MAIN: "Das ist eine Rückkopplung!",
            FIX_MESSAGE_0: "Nutze ",
            FIX_MESSAGE_1: "Verzögerungsblöcke",
            FIX_MESSAGE_2: " um sie zu verhindern.",
        },
        KEYBOARD: {
            CTRL_PC: "STRG",
            META_MAC: "⌘",
            ALT_PC: "ALT",
            ALT_MAC: "⌥",
            SHIFT: "SHIFT",
        },
        TIPS: {
            MOVE_NODE: "Knoten verschieben",
            DISCONNECT: "Kabel von Eingang trennen",
            INTERACT: "Interargieren",
            MOVE_BLOCK: "Block verschieben",
        },
        POPUPS: {
            OPEN_FILE: "Datei öffnen",
            CLEAR_WARING: "Dein aktueller Schaltkreis wird permanent gelöscht. Willst du wirklich fortfahren?",
            CLEAR_AND_CONTINUE: "Löschen & Fortfahren",
            CANCEL: "Abbrechen",
            ERROR_WHILE_UPLOADING: "Ein Fehler ist aufgetreten!",
            
            DOWNLOAD_AND_SHARE: "Herunterladen & Teilen",
            COPY_LINK: "Link kopieren",
            FORMAT: "Format",
            BINARY: "Binär",
            BINARY_NOTE: "Kleinere Datei (empfohlen)",
            JSON: "JSON",
            JSON_NOTE: "Bessere Lesbarkeit",
            FILE_NAME: "Dateiname",
            DOWNLOAD: "Herunterladen",
        }
    }
}

export const LANG = signals.value<"en_us" | "de_de">("en_us");